num1=int(input("enter your 1st number:"))
num2=int(input("enter your 2nd number:"))
num3=int(input("enter your 3rd number:"))
print("The sum of num1 and num2 is:", num1+num2)
print("The difference when num2 is subtracted from num1 is:", num1-num2)
print("The product of num1 and num2 is:", num1*num2)
print("The quotient when num1 is divided by num2 is:", num1/num2)
print("The remainder when num1 is divided by num2 is:", num1%num2)
result= (num1 + num2) * num3 /2
print("The result of (num1 + num2) * num3 / 2 is:",result)